In [399]:
import os
import pandas as pd
import numpy as np
import re
PUIdata = os.getenv('PUIDATA')

%matplotlib inline

In [200]:
data = pd.read_csv('/projects/open/NYCOpenData/nycopendata/data/erm2-nwe9/1446832678/erm2-nwe9')

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (8,17,39,40,47,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [343]:
data.head(100)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,31911011,11/05/2015 02:59:15 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11224,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.573431,-73.991742,"(40.57343122248129, -73.99174247588253)"
1,31908754,11/05/2015 02:09:49 AM,NaN,CHALL,CHALL,Opinion for the Mayor,HOUSING,NaN,NaN,NaN,...,NaN,NaN,NaN,1-1-1173130914,NaN,NaN,NaN,NaN,NaN,NaN
2,31910423,11/05/2015 02:06:51 AM,NaN,DPR,Department of Parks and Recreation,Root/Sewer/Sidewalk Condition,Trees and Sidewalks Program,Street,11234,1157 EAST 57 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625004,-73.920726,"(40.62500363580505, -73.92072558378698)"
3,31909924,11/05/2015 02:02:20 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11218,722 EAST 4 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634522,-73.974790,"(40.634522428879706, -73.97479041437481)"
4,31913310,11/05/2015 01:57:20 AM,11/05/2015 01:57:31 AM,HRA,HRA Benefit Card Replacement,Benefit Card Replacement,Medicaid,NYC Street Address,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,31914148,11/05/2015 01:55:55 AM,NaN,DOT,Department of Transportation,Highway Condition,Pothole - Highway,Highway,10304,NaN,...,Staten Island Expwy,East/Brooklyn Bound,Roadway,Clove Rd/Richmond Rd (Exit 13) - Lily Pond Ave...,NaN,NaN,NaN,40.606875,-74.085408,"(40.60687536641399, -74.0854077221027)"
6,31912764,11/05/2015 01:55:37 AM,NaN,DPR,DPR,Agency Issues,New Tree Complaint,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,31912611,11/05/2015 01:47:12 AM,NaN,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10021,1402 2 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.769379,-73.957930,"(40.769378795761845, -73.95793023233308)"
8,31913909,11/05/2015 01:39:31 AM,11/05/2015 02:35:44 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,11231,273 SMITH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.682614,-73.993240,"(40.682613541568664, -73.99323966551619)"
9,31914856,11/05/2015 01:38:35 AM,11/05/2015 02:33:33 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Store/Commercial,11231,273 SMITH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.682614,-73.993240,"(40.682613541568664, -73.99323966551619)"
10,31911308,11/05/2015 01:37:14 AM,NaN,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10465,279 PRENTISS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.820622,-73.810014,"(40.820622268305286, -73.81001443391547)"
11,31909392,11/05/2015 01:36:43 AM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint,NaN,10022,850 3 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.756924,-73.969976,"(40.75692417775419, -73.96997589542615)"
12,31912284,11/05/2015 01:30:36 AM,11/05/2015 02:13:35 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11221,23 CEDAR STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.696368,-73.928737,"(40.69636767790248, -73.92873677664315)"
13,31911299,11/05/2015 01:28:52 AM,11/05/2015 03:08:36 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11373,79-10 ELKS ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.732957,-73.886138,"(40.73295679547021, -73.8861384813844)"
14,31909030,11/05/2015 01:27:21 AM,11/05/2015 02:03:06 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10027,3155 BROADWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.814536,-73.959144,"(40.81453554135292, -73.95914444206745)"
15,31909884,11/05/2015 01:20:26 AM,NaN,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11210,1557 EAST 23 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612677,-73.950966,"(40.6126771783895, -73.95096598523156)"
16,31913776,11/05/2015 01:14:58 AM,11/05/2015 02:50:37 AM,NYPD,New York City Police Department,Noise - Commercial,Banging/Pounding,Store/Commercial,10036,204 WEST 47 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.759548,-73.985464,"(40.759548404216886, -73.98546383375366)"
17,31911881,11/05/2015 01:13:34 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11230,657 OCEAN PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.632159,-73.971974,"(40.632158514338116, -73.97197392871156)"
18,31913779,11/05/2015 01:11:44 AM,11/05/2015 01:59:55 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10013,32 WATTS STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723585,-74.004517,"(40.723584761323856, -74.00451687583916)"
19,31915178,11/05/2015 01:10:11 AM,11/05/2015 02:53:47 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11419,104-30 109 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683689,-73.832795,"(40.68368897953358, -73.83279520138734)"
20,31907956,11/05/2015 01:07:17 AM,11/05/2015 02:39:12 AM,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,11358,43-20 167 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758000,-73.799602,"(40.757999900269, -73.79960247910847)"
21,31913892,11/05/2015 01:06:28 AM,NaN,DPR,Department of Parks and Recreation,Damaged Tree,Branch or Limb Has Fallen Down,NaN,11101,23-16 45TH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.746617,-73.944772,"(40.74661655879547, -73.94477184350308)"
22,31910149,11/05/2015 01:00:42 AM,NaN,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10010,123 EAST 24 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.740417,-73.984829,"(40.7404174308271, -73.98482927836473)"
23,31910350,11/05/2015 12:59:14 AM,11/05/2015 02:27:18 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11214,76 BAY 31 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.600144,-73.994444,"(40.600143786620116, -73.99444356702752)"
24,31913895,11/05/2015 12:58:57 AM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint,NaN,11385,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.705033,-73.908988,"(40.70503271022964, -73.90898790311351)"
25,31913898,11/05/2015 12:58:13 AM,11/05/2015 01:30:23 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11207,123 JAMAICA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.678922,-73.895828,"(40.678921524875875, -73.8958280872322)"
26,31910446,11/05/2015 12:57:00 AM,NaN,DOT,Department of Transportation,Traffic Signal Condition,Ped Multiple Lamps,NaN,11385,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.700499,-73.900201,"(40.7004993066336, -73.90020149091094)"
27,31912897,11/05/2015 12:56:49 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11415,84-46 130 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.704888,-73.822715,"(40.704888248872315, -73.82271533783924)"
28,31913287,11/05/2015 12:56:00 AM,NaN,DOT,Department of Transportation,Traffic Signal Condition,Ped Multiple Lamps,NaN,11385,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.701968,-73.880497,"(40.701968198847794, -73.88049664749286)"
29,31909985,11/05/2015 12:55:56 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11415,84-39 130 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.704918,-73.822701,"(40.70491841899999, -73.82270083070199)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,31912598,11/05/2015 12:10:22 AM,NaN,CHALL,CHALL,Opinion for the Mayor,HOUSING,NaN,NaN,NaN,...,NaN,NaN,NaN,1-1-1173130684,NaN,NaN,NaN,NaN,NaN,NaN
71,31914808,11/05/2015 12:09:37 AM,11/05/2015 02:17:47 AM,NYPD,New York City Police Department,Posting Advertisement,Building,Residential Building/House,11219,1264 44 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.638348,-73.990088,"(40.63834825353327, -73.99008781686723)"
72,31911630,11/05/2015 12:09:21 AM,NaN,CHALL,CHALL,Opinion for the Mayor,PUBLICSAFETY,NaN,NaN,NaN,...,NaN,NaN,NaN,1-1-1173130679,NaN,NaN,NaN,NaN,NaN,NaN
73,31908728,11/05/2015 12:06:43 AM,NaN,DOT,Department of Transportation,Street Condition,Failed Street Repair,Street,10016,240 EAST 32 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.744012,-73.978062,"(40.7440119641058, -73.97806189509316)"
74,31910014,11/05/2015 12:06:09 AM,NaN,NYPD,New York City Police Department,Homeless Encampment,NaN,Street/Sidewalk,11226,2160 CATON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.652968,-73.958386,"(40.65296810753562, -73.95838565453022)"
75,31908386,11/05/2015 12:05:51 AM,NaN,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10031,560 WEST 144 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.825222,-73.949693,"(40.82522248363238, -73.94969287279021)"
76,31912323,11/05/2015 12:05:05 AM,NaN,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11412,111-21 205 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.704730,-73.751815,"(40.70472976477178, -73.7518148845826)"
77,31912756,11/05/2015 12:05:00 AM,11/05/2015 12:21:24 AM,NYPD,New York City Police Department,Illegal Parking,Unauthorized Bus Layover,Street/Sidewalk,11219,4305 FORT HAMILTON PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.641156,-73.993482,"(40.64115641211891, -73.9934816816124)"
78,31915575,11/05/2015 12:05:00 AM,NaN,DOT,Department of Transportation,Street Light Condition,Street Light Out,NaN,11212,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.663393,-73.913997,"(40.663392865381105, -73.91399726503518)"
79,31908183,11/05/2015 12:04:09 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11436,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.667068,-73.793066,"(40.66706786430971, -73.79306643645447)"
80,31913824,11/05/2015 12:04:09 AM,11/05/2015 01:23:45 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10025,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.802346,-73.968110,"(40.802346308210176, -73.96810967706041)"
81,31908082,11/05/2015 12:03:44 AM,11/05/2015 12:29:50 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10025,107 WEST 109 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.801411,-73.962002,"(40.80141124989614, -73.96200232327737)"
82,31910679,11/05/2015 12:02:56 AM,NaN,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10002,39 ESSEX STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.716135,-73.989467,"(40.71613509166252, -73.98946661078074)"
83,31908954,11/05/2015 12:02:06 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11358,33 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.767627,-73.798750,"(40.76762699717518, -73.79875040300837)"
84,31912863,11/05/2015 12:01:18 AM,11/05/2015 02:23:04 AM,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,11224,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.577543,-73.997876,"(40.577543215593856, -73.99787609452332)"
85,31909286,11/05/2015 12:01:18 AM,NaN,DSNY,Commissioner - EC,Agency Issues,Enforcement Issue,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,31910125,11/04/2015 11:59:11 PM,NaN,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10030,672 SAINT NICHOLAS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.823085,-73.945200,"(40.82308504635165, -73.94519976314912)"
87,31909865,11/04/2015 11:58:50 PM,11/05/2015 12:43:39 AM,NYPD,New York City Police Department,Illegal Parking,Unauthorized Bus Layover,Street/Sidewalk,11218,4024 FORT HAMILTON PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642537,-73.991449,"(40.642536906014875, -73.9914492595011)"
88,31914245,11/04/2015 11:58:48 PM,NaN,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11236,735 EAST 82 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.637369,-73.912784,"(40.63736865384849, -73.91278414327958)"
89,31913625,11/04/2015 11:58:11 PM,NaN,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,11385,1819 GEORGE STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.699539,-73.901162,"(40.699539466837884, -73.90116223796252)"
90,31910712,11/04/2015 11:58:00 PM,NaN,DOT,Department of Transportation,Street Light Condition,Street Light Out,NaN,11367,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.715804,-73.824476,"(40.71580414459643, -73.82447553099988)"
91,31908030,11/04/2015 11:56:34 PM,11/05/2015 02:26:15 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10012,281 LAFAYETTE STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.724013,-73.996194,"(40.72401296921459, -73.99619382218174)"
92,31912369,11/04/2015 11:56:23 PM,11/05/2015 01:42:03 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11385,64-30 68 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.705991,-73.893420,"(40.70599099528962, -73.89341973908742)"
93,31909975,11/04/2015 11:55:42 PM,11/05/2015 01:06:24 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10036,667 10 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.762535,-73.993365,"(40.76253541094182, -73.99336511754211)"
94,31909311,11/04/2015 11:55:03 PM,NaN,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10459,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.826743,-73.887897,"(40.82674345592527, -73.88789667181122)"
95,31911048,11/04/2015 11:54:31 PM,11/05/2015 01:57:51 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,11233,651 HANCOCK STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.684974,-73.928900,"(40.68497423684428, -73.92890038959827)"
96,31911877,11/04/2015 11:54:31 PM,11/05/2015 01:01:46 AM,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,11691,1122 GRASSMERE TERRACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.604528,-73.756876,"(40.60452822282147, -73.75687627646387)"
97,31914235,11/04/2015 11:51:55 PM,11/05/2015 01:37:47 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10026,318 WEST 118 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.806012,-73.955118,"(40.80601168021016, -73.95511846289004)"
98,31915177,11/04/2015 11:50:32 PM,NaN,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Horn,Street/Sidewalk,11209,601 79 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.624966,-74.021276,"(40.62496586845221, -74.0212757601525)"
99,31911338,11/04/2015 11:50:10 PM,11/05/2015 02:14:39 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11373,41-07 DENMAN STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.746479,-73.874448,"(40.74647902682749, -73.87444756580243)"

In [201]:
datareduced = data.copy()

In [202]:
datareduced.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,31911011,11/05/2015 02:59:15 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,11224,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.573431,-73.991742,"(40.57343122248129, -73.99174247588253)"
1,31908754,11/05/2015 02:09:49 AM,NaN,CHALL,CHALL,Opinion for the Mayor,HOUSING,NaN,NaN,NaN,...,NaN,NaN,NaN,1-1-1173130914,NaN,NaN,NaN,NaN,NaN,NaN
2,31910423,11/05/2015 02:06:51 AM,NaN,DPR,Department of Parks and Recreation,Root/Sewer/Sidewalk Condition,Trees and Sidewalks Program,Street,11234,1157 EAST 57 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.625004,-73.920726,"(40.62500363580505, -73.92072558378698)"
3,31909924,11/05/2015 02:02:20 AM,NaN,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11218,722 EAST 4 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634522,-73.974790,"(40.634522428879706, -73.97479041437481)"
4,31913310,11/05/2015 01:57:20 AM,11/05/2015 01:57:31 AM,HRA,HRA Benefit Card Replacement,Benefit Card Replacement,Medicaid,NYC Street Address,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [203]:
len(datareduced["Community Board"].unique())

77

In [190]:
datareduced["Community Board"].unique()

array(['13 BROOKLYN', '0 Unspecified', '18 BROOKLYN', '12 BROOKLYN',
       '02 STATEN ISLAND', '08 MANHATTAN', '06 BROOKLYN', '10 BRONX',
       '06 MANHATTAN', '04 BROOKLYN', '04 QUEENS', '09 MANHATTAN',
       '14 BROOKLYN', '05 MANHATTAN', '02 MANHATTAN', '10 QUEENS',
       '07 QUEENS', '02 QUEENS', '11 BROOKLYN', '05 QUEENS', '05 BROOKLYN',
       '09 QUEENS', '12 MANHATTAN', '01 BROOKLYN', '11 MANHATTAN',
       '03 BRONX', '03 STATEN ISLAND', '08 BROOKLYN', '03 BROOKLYN',
       '07 MANHATTAN', '10 MANHATTAN', '04 BRONX', '01 MANHATTAN',
       '07 BRONX', '09 BRONX', '03 MANHATTAN', '13 QUEENS', '02 BRONX',
       '12 QUEENS', '16 BROOKLYN', '08 QUEENS', '04 MANHATTAN',
       '14 QUEENS', '10 BROOKLYN', '11 QUEENS', '06 BRONX', '08 BRONX',
       '05 BRONX', '15 BROOKLYN', '02 BROOKLYN', '12 BRONX', '03 QUEENS',
       '06 QUEENS', '01 STATEN ISLAND', '01 BRONX', '01 QUEENS',
       '17 BROOKLYN', '11 BRONX', 'Unspecified QUEENS', '09 BROOKLYN',
       'Unspecified MANHATTAN', 'Unspecified BROOKLYN', '07 BROOKLYN',
       'Unspecified BRONX', '64 MANHATTAN', '81 QUEENS', '55 BROOKLYN',
       '83 QUEENS', 'Unspecified STATEN ISLAND', '28 BRONX', '80 QUEENS',
       '26 BRONX', '95 STATEN ISLAND', '82 QUEENS', '27 BRONX',
       '56 BROOKLYN', '84 QUEENS'], dtype=object)

#### How many unique values do we have?
There are 74 unique community districts in the data.
#### Why do we have so many? Some of them are unspecified, missing. Some might be invalid entries. (We should have 59 Community Districts.)
There are more than 59 unique values because some are 'unspecified'. All boroughs are represented, however Staten Island only has one Community District included in the data.

In [204]:
len(datareduced)

10187766

In [205]:
datareduced.drop_duplicates().shape

(10187766, 53)

#### There are no duplicate rows in this dataset.

In [207]:
datareduced.isnull().sum()

Unique Key                               0
Created Date                             0
Closed Date                         450879
Agency                                   0
Agency Name                              0
Complaint Type                           0
Descriptor                           31057
Location Type                      3067596
Incident Zip                        794159
Incident Address                   2197706
Street Name                        2198559
Cross Street 1                     2375943
Cross Street 2                     2425793
Intersection Street 1              8345288
Intersection Street 2              8346302
Address Type                        490299
City                                788712
Landmark                          10180456
Facility Type                      8579485
Status                                   0
Due Date                           7120286
Resolution Description             3786751
Resolution Action Updated Date      250934
Community Board                          0
Borough                                  0
X Coordinate (State Plane)          878752
Y Coordinate (State Plane)          878752
Park Facility Name                       0
Park Borough                             0
School Name                              0
School Number                         2283
School Region                        56197
School Code                          56196
School Phone Number                      0
School Address                           6
School City                              0
School State                             0
School Zip                               5
School Not Found                   7151698
School or Citywide Complaint      10185412
Vehicle Type                      10180264
Taxi Company Borough              10177601
Taxi Pick Up Location             10089207
Bridge Highway Name               10152671
Bridge Highway Direction          10152723
Road Ramp                         10152986
Bridge Highway Segment            10135780
Garage Lot Name                   10183433
Ferry Direction                   10185023
Ferry Terminal Name               10181242
Latitude                            878752
Longitude                           878752
Location                            878752
dtype: int64

There are cells with missing values. Columns 'Landmark', 'School or Citywide Complaint', 'Vehicle Type', 'Taxi Company Borough', 'Garage Lot Name', 'Ferry Direction', and 'Ferry Terminal Name' contain exclusively null values. Similarly, 'Bridge Highway Name', 'Bridge Highway Direction', and 'Road Ramp' only contain one non-null value. Community Board does not have any null values.

In [211]:
datareduced["Resolution Description"].fillna(datareduced["Complaint Type"], inplace=True)

In [214]:
datareduced["Resolution Description"].isnull().sum()

0

#### The unplausible Community Districts are those which include the word 'unspecified' in the title and the Community Districts with numbers greater than 18

In [234]:
def flag(data):
    if re.search(r"Unspecified", data):
        return 0
    elif int(re.search(r"(\d\d*)\s\w+", data).group(1))>18:
        return 0
    else:
        return 1

In [249]:
mask = datareduced["Community Board"].apply(flag)

In [250]:
datareduced["masks"] = mask

In [251]:
datanew = datareduced[datareduced.masks==1]

In [256]:
datanew["Community Board"].unique().shape

(59,)

In [257]:
ranks = datanew["Complaint Type"].groupby(datanew["Community Board"]).count()

In [258]:
ranks = pd.DataFrame(ranks)

In [379]:
ranking = ranks.reset_index().sort(columns=["Complaint Type"], ascending=False).reset_index(drop=True)

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [381]:
ranking = ranking.rename(columns = {'Complaint Type':'counts'})

In [382]:
ranking.head()

  Community Board  counts
0    12 MANHATTAN  268053
1       12 QUEENS  229383
2     03 BROOKLYN  197306
3       07 QUEENS  195961
4     17 BROOKLYN  191720

In [261]:
df_pop = pd.read_csv(PUIdata + "/Final_Demographics.csv")
df_infr = pd.read_csv(PUIdata + "/ACS_Computer_Use_and_Internet_2014_1Year_Estimate.csv")

In [262]:
df_infr.head()

,FIPS,Geographic Identifier,Qualifying Name,Households,Households: With An Internet Subscription,Households: Dial-Up Alone,Households: Dsl,Households: With Mobile Broadband,Households: Without Mobile Broadband,Households: Cable Modem,...,Households: Mobile Broadband Alone or With Dialup,Households: Internet Access Without A Subscription,Households: No Internet Access,% Households: With An Internet Subscription,Households.1,Households: Has A Computer,Households: With Dial-Up Internet Subscription Alone,Households: With A Broadband Internet Subscription,Households: Without An Internet Subscription,Households: No Computer
0,3603701,79500US3603701,"NYC-Bronx Community District 8--Riverdale, New...",42035,31795,444,2813,946,1867,19178,...,2168,2119,8121,75.64,42035,35048,404,30943,3701,6987
1,3603702,79500US3603702,"NYC-Bronx Community District 12--Wakefield, Ne...",44830,32243,178,849,405,444,18653,...,928,1891,10696,71.92,44830,36700,178,31435,5087,8130
2,3603703,79500US3603703,"NYC-Bronx Community District 10--Co-op City, N...",47050,32729,158,1863,398,1465,20044,...,639,2882,11439,69.56,47050,38700,158,32333,6209,8350
3,3603704,79500US3603704,NYC-Bronx Community District 11--Pelham Parkwa...,44922,32003,141,1478,474,1004,17917,...,1001,2722,10197,71.24,44922,37237,122,31278,5837,7685
4,3603705,79500US3603705,"NYC-Bronx Community District 3 & 6--Belmont, N...",57556,35503,88,1297,651,646,15847,...,1385,3312,18741,61.68,57556,42576,88,33408,9080,14980

In [263]:
df_pop.head()

,FIPS,cd_id,Total Population,Population Density (per sq. mile),% Total Population: Male,% Total Population: 18 to 24 Years,% Total Population: 25 to 34 Years,% Total Population: 35 to 44 Years,% Population 5 Years And Over: Speak Only English,% Population 5 Years And Over: Spanish or Spanish Creole,...,"Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Production occupations","Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Transportation and material moving occupations","% Employed Civilian Population 16 Years And Over: Management, professional, and related occupations",% Employed Civilian Population 16 Years And Over: Service occupations,% Employed Civilian Population 16 Years And Over: Sales and office occupations,"% Employed Civilian Population 16 Years And Over: Farming, fishing, and forestry occupations","% Employed Civilian Population 16 Years And Over: Construction, extraction, and maintenance occupations","% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations","% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Production occupations","% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving occupations: Transportation and material moving occupations"
0,3603701,BX08,106737,31229.95006,46.65,10.73,15.04,11.32,46.80,39.24,...,665,1518,42.66,28.95,20.89,0.24,2.65,4.60,1.40,3.20
1,3603702,BX12,134644,19966.67839,46.35,11.35,14.29,12.57,73.09,18.19,...,1156,4174,29.57,33.98,20.40,0.00,7.08,8.97,1.95,7.02
2,3603703,BX10,121209,12913.81703,45.20,8.62,13.74,12.78,61.79,26.43,...,941,3433,36.20,22.85,25.09,0.00,7.68,8.18,1.76,6.42
3,3603704,BX11,135839,35677.95453,50.09,8.10,17.43,14.09,43.22,36.45,...,2189,5592,30.06,27.86,22.24,0.00,7.03,12.81,3.60,9.20
4,3603705,BX03,172247,39405.79222,44.72,14.24,14.89,12.38,36.82,54.24,...,1437,5436,16.80,41.00,22.29,0.03,8.45,11.43,2.39,9.04

In [269]:
df_pop.columns

Index(['FIPS', 'cd_id', 'Total Population',
       'Population Density (per sq. mile)', '% Total Population: Male',
       '% Total Population: 18 to 24 Years',
       '% Total Population: 25 to 34 Years',
       '% Total Population: 35 to 44 Years',
       '% Population 5 Years And Over: Speak Only English',
       '% Population 5 Years And Over: Spanish or Spanish Creole',
       ...
       'Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Production occupations',
       'Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Transportation and material moving occupations',
       '% Employed Civilian Population 16 Years And Over: Management, professional, and related occupations',
       '% Employed Civilian Population 16 Years And Over: Service occupations',
       '% Employed Civilian Population 16 Years And Over: Sales and office occupations',
       '% Employed Civilian Population 16 Years And Over: Farming, fishing, and forestry occupations',
       '% Employed Civilian Population 16 Years And Over: Construction, extraction, and maintenance  occupations',
       '% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations',
       '% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Production occupations',
       '% Employed Civilian Population 16 Years And Over: Production, transportation, and material moving  occupations: Transportation and material moving occupations'],
      dtype='object', length=158)

In [264]:
df_pop["cd_id"].unique().shape

(59,)

In [298]:
demograph = df_pop[["cd_id", "Median household income (In 2014 Inflation Adjusted Dollars)"]]

#### Normally order people or people with families tend to make compliants

In [270]:
df_infr.columns

Index(['FIPS', 'Geographic Identifier', 'Qualifying Name', 'Households',
       'Households: With An Internet Subscription',
       'Households: Dial-Up Alone', 'Households: Dsl',
       'Households: With Mobile Broadband',
       'Households: Without Mobile Broadband', 'Households: Cable Modem',
       'Households: With Mobile Broadband.1',
       'Households: Without Mobile Broadband.1', 'Households: Fiber-Optic',
       'Households: With Mobile Broadband.2',
       'Households: Without Mobile Broadband.2',
       'Households: Satellite Internet Service',
       'Households: With Mobile Broadband.3',
       'Households: Without Mobile Broadband.3',
       'Households: Two or More Fixed Broadband Types, or Other',
       'Households: With Mobile Broadband.4',
       'Households: Without Mobile Broadband.4',
       'Households: Mobile Broadband Alone or With Dialup',
       'Households: Internet Access Without A Subscription',
       'Households: No Internet Access',
       '% Households: With An Internet Subscription', 'Households.1',
       'Households: Has A Computer',
       'Households: With Dial-Up Internet Subscription Alone',
       'Households: With A Broadband Internet Subscription',
       'Households: Without An Internet Subscription',
       'Households: No Computer'],
      dtype='object')

In [272]:
df_infr["Qualifying Name"].unique().shape

(55,)

In [308]:
mobile = df_infr.iloc[:,[2, 7, 10, 13, 16, 19, 21]]

In [309]:
mobile['Mobile'] = mobile.sum(axis=1)

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [310]:
# no mobile
nobile =  df_infr.iloc[:,[2, 8, 11, 14, 17, 20, 22]]

In [311]:
nobile['Nobile'] = nobile.sum(axis=1)

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [312]:
mobile_info = pd.concat([mobile, nobile], axis=1)

In [316]:
mobile_info = mobile_info.iloc[:,[0, 7, 15]]

In [317]:
mobile_info.head()

                                     Qualifying Name  Mobile  Nobile
0  NYC-Bronx Community District 8--Riverdale, New...   17527   15943
1  NYC-Bronx Community District 12--Wakefield, Ne...   11414   22542
2  NYC-Bronx Community District 10--Co-op City, N...   12064   23389
3  NYC-Bronx Community District 11--Pelham Parkwa...   11749   22835
4  NYC-Bronx Community District 3 & 6--Belmont, N...   16292   22435

In [294]:
high_speed =  df_infr.iloc[:,[2, 6, 9, 12]]
high_speed['High'] = high_speed.sum(axis=1)
low_speed = df_infr.iloc[:, [2, 5, 15]]
low_speed['Low'] = low_speed.sum(axis=1)
it_info = pd.concat([high_speed, low_speed], axis=1)
it_info = it_info.ix[:,[0,4, 8]]

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [295]:
it_info.head()

                                     Qualifying Name   High  Low
0  NYC-Bronx Community District 8--Riverdale, New...  22930  519
1  NYC-Bronx Community District 12--Wakefield, Ne...  25718  309
2  NYC-Bronx Community District 10--Co-op City, N...  25397  158
3  NYC-Bronx Community District 11--Pelham Parkwa...  24830  449
4  NYC-Bronx Community District 3 & 6--Belmont, N...  18654  282

In [89]:
def converter_1(data):
    if re.search(r"Bronx", data, re.IGNORECASE):
        return re.sub(r"(\d\d)\s.+", r"BX\1", data)
    elif re.search(r"Queen", data, re.IGNORECASE):
        return re.sub(r"(\d\d)\s.+", r"QN\1", data)
    elif re.search(r"STATEN ISLAND", data, re.IGNORECASE):
        return re.sub(r"(\d\d)\s.+", r"SI\1", data)
    elif re.search(r"BROOKLYN", data, re.IGNORECASE):
        return re.sub(r"(\d\d)\s.+", r"BK\1", data)
    elif re.search(r"manhattan", data, re.IGNORECASE):
        return re.sub(r"(\d\d)\s.+", r"MN\1", data)

In [367]:
pat1 = re.compile(r"\w+-\w+\s*\w*\s\w+\s\w+\s(\d\d)\s*&*\d*.*", re.IGNORECASE)
pat2 = re.compile(r"\w+-\w+\s*\w*\s\w+\s\w+\s(\d)\s*&*\d*.*", re.IGNORECASE)

In [296]:
def converter_2(data):
    if re.search(r"Bronx", data,re.IGNORECASE):
        if re.search(pat1, data):
            return re.sub(pat1, r"BX\1", data)
        else:
            return re.sub(pat2, r"BX0\1", data)
    elif re.search(r"Queen", data,re.IGNORECASE):
         if re.search(pat1, data):
            return re.sub(pat1, r"QN\1", data)
         else:
            return re.sub(pat2, r"QN0\1", data)
    elif re.search(r"STATEN ISLAND", data, re.IGNORECASE):
         if re.search(pat1, data, ):
            return re.sub(pat1, r"SI\1", data)
         else:
            return re.sub(pat2, r"SI0\1", data)
    elif re.search(r"BROOKLYN", data, re.IGNORECASE):
         if re.search(pat1, data):
            return re.sub(pat1, r"BK\1", data)
         else:
            return re.sub(pat2, r"BK0\1", data)
    elif re.search(r"manhattan", data, re.IGNORECASE):
         if re.search(pat1, data):
            return re.sub(pat1, r"MN\1", data)
         else:
            return re.sub(pat2, r"MN0\1", data)

In [372]:
demo = demograph.drop_duplicates(subset="Median household income (In 2014 Inflation Adjusted Dollars)")

In [373]:
demo = demo.rename(columns = {'cd_id':'district'})

In [404]:
demo["district"][demo["district"]=="MN05"] = "MN04"

/opt/rh/anaconda/root/envs/PUI2016_Python3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [374]:
first = mobile_info.merge(it_info, on="Qualifying Name")

In [375]:
first["district"] = first["Qualifying Name"].apply(converter_2)

In [376]:
first.drop(["Qualifying Name"], axis=1, inplace=1)

In [377]:
first.drop_duplicates(inplace=1)

In [383]:
ranking["district"] = ranking["Community Board"].apply(converter_1)

In [384]:
ranking.drop(["Community Board"], axis=1, inplace=1)

In [385]:
ranking = ranking.drop_duplicates(subset="counts")

In [406]:
final = demo.merge(first, on="district", how="inner").merge(ranking, on="district", how="inner")

In [407]:
final

,district,Median household income (In 2014 Inflation Adjusted Dollars),Mobile,Nobile,High,Low,counts
0,BX08,54224,17527,15943,22930,519,92733
1,BX12,44906,11414,22542,25718,309,168455
2,BX10,54962,12064,23389,25397,158,95496
3,BX11,47910,11749,22835,24830,449,122081
4,BX03,22041,16292,22435,18654,282,75134
5,BX07,35495,16709,19414,22626,0,185729
6,BX05,20872,15857,13401,12431,415,161078
7,BX04,27203,18342,14419,16053,732,181953
8,BX09,36058,12892,34775,32042,669,147457
9,BX01,21116,15981,19144,20357,1145,74631
10,MN12,45157,26592,32179,46246,1799,268053
11,MN09,42235,17556,19398,25311,1411,127565
12,MN10,40564,14746,24282,29162,434,137344
13,MN11,31340,10434,21535,25515,854,95413
14,MN08,115238,63973,41971,91094,824,149076
15,MN07,106181,49546,38942,70052,533,151419
16,MN04,98561,34994,38350,61180,329,132660
17,MN06,105625,39450,32440,63014,758,104249
18,MN03,41366,20868,29983,39186,577,150296
19,MN01,120190,41450,36201,66178,590,77974
20,SI03,82718,14334,36705,41521,331,136487
21,SI02,71459,11206,24922,28739,652,121132
22,SI01,57602,11151,37213,41169,454,182713
23,BK01,57818,21459,27556,41013,598,185057
24,BK04,40484,14171,21045,25691,139,139706
25,BK03,34678,12648,22363,25803,754,197306
26,BK02,84568,18679,29429,40267,562,121022
27,BK06,113045,23815,21612,39648,356,114029
28,BK08,44904,10559,26275,30716,533,141119
29,BK16,25259,5927,21433,21920,496,85467
30,BK05,32996,9572,29604,32455,512,189765
31,BK18,62090,19215,37513,42148,507,156100
32,BK17,42349,13596,23007,30543,622,191720
33,BK09,41814,8591,20994,24066,898,135833
34,BK07,48051,12123,24663,31085,290,107031
35,BK10,56696,19341,20053,27671,735,111837
36,BK12,43222,11935,18323,21860,539,150320
37,BK14,50316,16540,30443,37764,629,187794
38,BK15,52717,13969,27857,31439,870,146129
39,BK11,47748,17710,30758,33148,831,139890
40,BK13,29578,7779,21548,22323,492,72362
41,QN01,56269,31144,32255,54294,769,171484
42,QN03,49610,9750,32139,35375,427,122009
43,QN07,52105,23421,46121,61711,347,195961
44,QN11,80866,16201,21702,31966,314,101908
45,QN13,75732,13931,37604,40306,1006,163851
46,QN08,55324,15239,29686,38680,310,123131
47,QN04,45264,8440,25775,28781,286,99316
48,QN06,61290,13715,28978,36487,710,90938
49,QN02,57265,14616,31087,39824,520,114333
50,QN05,63660,9845,39150,43904,681,168570
51,QN09,61275,11481,25492,29993,1243,151242
52,QN12,52537,15241,39630,40100,1817,229383
53,QN10,60946,10916,20230,23567,720,128116
54,QN14,44239,6905,23412,23831,523,103396